---
title: "Supplementary 1 - Preprocessing statistics"
author: "Glen Roarke"
date: "2023-08-09"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float: yes
    number_sections: yes
    fig_caption: yes
  word_document:
    toc: yes
    toc_depth: '3'

---

```{r install, eval=FALSE}
install.packages("vroom")
install.packages("tidyverse")
install.packages("ggplot2")
install.packages("stringr")
install.packages("patchwork")

```


```{r setup, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(vroom)
library(ggplot2)
library(tidyverse)
library(patchwork)

```


# Import and manipulate

The preprocessing results are merged together to compare sequencing information for each batch.

```{r import}

#input of b2 annotation
b1_preproc <- vroom("inputs/Batch1_preprocessing_stats_2023-06-27_11-43-51.csv")
b2_preproc <- vroom("inputs/Batch2_preprocessing_stats_2023-06-27_11-48-42.csv")
b3_preproc <- vroom("inputs/Batch3_preprocessing_stats_2023-06-27_11-53-18.csv")

sample_data <- vroom("inputs/sample_data.csv")
dna_conc <- sample_data %>% select(Sample ,QubitPreClean, TapestationPostClean, FinalLibraryConc, TotalDNAForLibPrep)

dna_conc

# add in batch information as a factor
b1_preproc$batch <- as.factor(1)
b2_preproc$batch <- as.factor(2)
b3_preproc$batch <- as.factor(3)

#merge 
preproc_all <- bind_rows(b1_preproc, b2_preproc, b3_preproc)

preproc_all_dna <- preproc_all %>% inner_join(dna_conc, by = c("sample_id" = "Sample"))


```


``` {R create plots}


# A - read mapping by batch 

read_map.p <-  ggplot(preproc_all, aes(y = Mapped_read_pairs, x = batch, fill = batch)) +
  geom_boxplot(alpha = 0.3, outlier.shape=NA) +
  geom_point(position=position_jitterdodge()) + 
  theme_classic() +
  ggtitle("Read Mapping pairs by sequencing batch") +
  ylab("Read mapping proportion")


# B - Depth of coverage 

#calculate mean depth to annotate graph
mean_depth_value <- mean(preproc_all$meandepth)

# plot depth per read
depth.p <- ggplot(preproc_all, aes(y = meandepth, x = batch, fill = batch)) +
  geom_boxplot(alpha = 0.3, outlier.shape=NA) +
  geom_point(position=position_jitterdodge()) + 
  theme_classic() +
  ggtitle("Depth of coverage by sequencing batch") +
  ylab("Mean depth") + annotate("text", x = 0.7, y = 1, label = sprintf("Mean %.2fx", mean_depth_value),
                                color = "black", size = 4, vjust = -1)


# C - read mapping by DNA concentration

dna_conc.p <- ggplot(preproc_all_dna, aes(y = Mapped_read_pairs, x = log10(TotalDNAForLibPrep), col = batch)) +
  geom_point() +
  geom_text(aes(label = sample_id), vjust = -1, size = 2, check_overlap = FALSE) +
  ggtitle("DNA concentration by read mapping") +
  theme_bw() +  
  geom_hline(yintercept=0.8, linetype='dotted', col = 'red') +
  annotate("text", x = 1, y = 0.78, label = "threshold", vjust = -0) +
  ylab("Read mapping proportion") +
  xlab("cfDNA (ng/microliter)")



```


``` {R pathwork plots, fig.height = 8}

### merge all graphs using patchwork

(depth.p / read_map.p / dna_conc.p)  + plot_annotation(tag_levels = "A")
ggsave("final_figures/Figure_2_ctDNA_preprocessing.pdf", height = 8 , width = 6 )

```




# sessionInfo
``` {R session info}


installed.packages()[names(sessionInfo()$otherPkgs), "Version"]
